version: '3.8'

services:
  typesense:
    image: typesense/typesense:26.0
    container_name: typesense
    volumes:
      - typesense-data:/data
    command: '--data-dir /data --api-key=xyz'
    network_mode: "host"

volumes:
  typesense-data:
    driver: local
